# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlbumCarousel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlbumCarousel
  pod 'Alamofire', '~> 4.0'
  pod 'Kingfisher', '~> 3.0'
end
